package seng201.team67.models.enums;

public enum SkillEffects {
    FLAT_STAMINA_BOOST,
    FLAT_STAR_POWER_BOOST,
    STAMINA_COST_REDUCTION,
    RETIREMENT_RISK,
    FLAT_CREDIT_BONUS,
    PAYOUT_MULTIPLIER,
    GREAT_PAYOUT_MULTIPLIER,
    TERRIBLE_PAYOUT_REDUCTION
}
